/* Dress constant */

export const DRESS_LIST_REQUEST = 'DRESS_LIST_REQUEST'
export const DRESS_LIST_SUCCESS  = 'DRESS_LIST_SUCCESS'
export const DRESS_LIST_FAIL = 'DRESS_LIST_FAIL'

export const DRESS_DETAILS_REQUEST = 'DRESS_DETAILS_REQUEST'
export const DRESS_DETAILS_SUCCESS  = 'DRESS_DETAILS_SUCCESS'
export const DRESS_DETAILS_FAIL = 'DRESS_DETAILS_FAIL'

export const DRESS_DELETE_REQUEST = 'DRESS_DELETE_REQUEST'
export const DRESS_DELETE_SUCCESS  = 'DRESS_DELETE_SUCCESS'
export const DRESS_DELETE_FAIL = 'DRESS_DELETE_FAIL'

export const DRESS_ADD_REQUEST = 'DRESS_ADD_REQUEST'
export const DRESS_ADD_SUCCESS  = 'DRESS_ADD_SUCCESS'
export const DRESS_ADD_FAIL = 'DRESS_ADD_FAIL'
export const DRESS_ADD_RESET = 'DRESS_ADD_RESET'

export const DRESS_UPDATE_REQUEST = 'DRESS_UPDATE_REQUEST'
export const DRESS_UPDATE_SUCCESS  = 'DRESS_UPDATE_SUCCESS'
export const DRESS_UPDATE_FAIL = 'DRESS_UPDATE_FAIL'
export const DRESS_UPDATE_RESET = 'DRESS_UPDATE_RESET'

export const DRESS_CREATE_REVIEW_REQUEST = 'DRESS_CREATE_REVIEW_REQUEST'
export const DRESS_CREATE_REVIEW_SUCCESS  = 'DRESS_CREATE_REVIEW_SUCCESS'
export const DRESS_CREATE_REVIEW_FAIL = 'DRESS_CREATE_REVIEW_FAIL'
export const DRESS_CREATE_REVIEW_RESET = 'DRESS_CREATE_REVIEW_RESET'

export const DRESS_TOP_REQUEST = 'DRESS_TOP_REQUEST'
export const DRESS_TOP_SUCCESS  = 'DRESS_TOP_SUCCESS'
export const DRESS_TOP_FAIL = 'DRESS_TOP_FAIL'
/* cart and shipping constant */

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

/* user constant */

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

/* order constant */

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'